### ISSUE TITLE
Uncaught exception 'RuntimeException' with message 'Accessed request service outside of request scope. Try moving that call to a before handler or controller.'

### ISSUE THREAD

**Issue by tacone** [CHH/frozen-silex#2]
Using more than one path inside a twig template, for example:

```
{{ path('homepage') }}
{{ path('detail') }}
```

provokes this error:

```
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Accessed request service outside of request scope. Try moving that call to a before handler or controller.' in /var/www/silex.loc/vendor/silex/silex/src/Silex/Application.php:132
Stack trace:
#0 /var/www/silex.loc/vendor/pimple/pimple/lib/Pimple.php(83): Silex\Application->Silex\{closure}(Object(Silex\Application))
#1 /var/www/silex.loc/vendor/twig/twig/lib/Twig/Template.php(350): Pimple->offsetGet('request')
#2 /var/www/silex.loc/resources/cache/twig/5f/11/5152923b2fab32ab1e825a35ddd0.php(133): Twig_Template->getAttribute(Object(Silex\Application), 'request')
#3 /var/www/silex.loc/vendor/twig/twig/lib/Twig/Template.php(264): __TwigTemplate_5f115152923b2fab32ab1e825a35ddd0->doDisplay(Array, Array)
#4 /var/www/silex.loc/vendor/twig/twig/lib/Twig/Template.php(238): Twig_Template->displayWithErrorHandling(Array, Array)
#5 /var/www/silex.loc/resources/cache/twig/15/b3/c164d92d3845aa53025eb7701142.php(26): Twig_Template->display(Array, Array)
#6 /var/www/silex.lo in /var/www/silex.loc/vendor/twig/twig/lib/Twig/Template.php on line 279
```

This is my freeze.php file:

``` php
<?php

require_once __DIR__.'/../vendor/autoload.php';

$app = new Silex\Application();

require __DIR__.'/../resources/config/prod.php';
require __DIR__.'/../src/app.php';
require __DIR__.'/../src/controllers.php';


$freezer = new \FrozenSilex\Freezer($app);
$freezer->freeze();
```

Leaving just one "path" in the twig view apparently works fine.

**Comment by CHH** [comment]
Interesting, tried to reproduce but works just fine here.

**Comment by CHH** [comment]
This example works just fine: https://github.com/CHH/frozen-silex/blob/master/example/views/layout.html

**Comment by tacone** [comment]
Could have been already solved on the silex side during the last few months.
